
CREATE TABLE dims.dim_briefing
( 
	briefing_key         integer  NOT NULL ,
	parent_briefing_key  integer  NULL ,
	clone_to_briefing_key integer  NULL ,
	clone_from_briefing_key integer  NULL ,
	briefing_id          integer  NULL ,
	ev_products_installed varchar(1400)  NULL ,
	additional_notes     varchar(2200)  NULL ,
	allow_attendee_access_with_pin boolean  NULL ,
	available_sections   varchar(250)  NULL ,
	background_notes     varchar(2500)  NULL ,
	account_overview     varchar(6400)  NULL ,
	city_state           varchar(1200)  NULL ,
	competitive_products_installed varchar(1000)  NULL ,
	current_nda_on_file  boolean  NULL ,
	customer_status      varchar(250)  NULL ,
	customers_issues     varchar(3400)  NULL ,
	industry             varchar(360)  NULL ,
	internal_meeting_type varchar(1000)  NULL ,
	opportunity_notes    varchar(2000)  NULL ,
	partner_details      varchar(700)  NULL ,
	post_briefing_available_sections varchar(300)  NULL ,
	pre_briefing_available_sections varchar(250)  NULL ,
	purpose_of_meeting   varchar(450)  NULL ,
	requestor_attending  boolean  NULL ,
	requestor_attending1 boolean  NULL ,
	requestor_role_title varchar(250)  NULL ,
	sales_agent_attending boolean  NULL ,
	sales_stage          varchar(250)  NULL ,
	scheduling_notes_header varchar(1500)  NULL ,
	solutions            varchar(250)  NULL ,
	staff_notes          varchar(4000)  NULL ,
	workday_key_meeting_objectives varchar(2000)  NULL ,
	technical_issues     varchar(2500)  NULL ,
	cancel_reason        varchar(250)  NULL ,
	cancelled_at         datetime  NULL ,
	cancelled_by         varchar(250)  NULL ,
	cep_enabled          boolean  NULL ,
	cep_media            varchar(450)  NULL ,
	cep_overview         varchar(250)  NULL ,
	cep_show_ext_attendee boolean  NULL ,
	cep_show_logistics   boolean  NULL ,
	cep_show_pre_survey  boolean  NULL ,
	cep_show_survey      boolean  NULL ,
	clone_notes          varchar(250)  NULL ,
	closed_at            datetime  NULL ,
	closed_by            varchar(250)  NULL ,
	cond_last_sync_at    datetime  NULL ,
	cond_sync_pending    varchar(250)  NULL ,
	cond_sync_status     varchar(250)  NULL ,
	conference_call_link varchar(250)  NULL ,
	confirmed_at         datetime  NULL ,
	confirmed_by         varchar(250)  NULL ,
	coordinator_email    varchar(250)  NULL ,
	created_at           datetime  NULL ,
	created_by           varchar(250)  NULL ,
	custom_other_comments varchar(260)  NULL ,
	customer_company     varchar(250)  NULL ,
	customer_logo        varchar(250)  NULL ,
	customer_objective   varchar(2500)  NULL ,
	deal_support_request_id varchar(1500)  NULL ,
	deleted_at           datetime  NULL ,
	display_on_ebc_calendar boolean  NULL ,
	end_time             date  NULL ,
	jn_updated           boolean  NULL ,
	jn_uuid              varchar(250)  NULL ,
	notified_cc          varchar(300)  NULL ,
	notified_to          varchar(250)  NULL ,
	pin                  varchar(250)  NULL ,
	preferred_date       datetime  NULL ,
	preferred_end_date   datetime  NULL ,
	preferred_end_time   date  NULL ,
	preferred_start_time date  NULL ,
	related_briefings    varchar(250)  NULL ,
	request_submitted_at datetime  NULL ,
	requestor_email      varchar(250)  NULL ,
	requestor_name       varchar(250)  NULL ,
	requestor_phone      varchar(250)  NULL ,
	rfp_description      varchar(250)  NULL ,
	rfp_opportunity_id   varchar(250)  NULL ,
	r_rule               varchar(250)  NULL ,
	scheduled_date       datetime  NULL ,
	scheduled_end_date   datetime  NULL ,
	scheduling_notes     varchar(250)  NULL ,
	sfdc_update_required boolean  NULL ,
	start_time           date  NULL ,
	team_url             varchar(250)  NULL ,
	tech_support_email   varchar(250)  NULL ,
	title                varchar(250)  NULL ,
	title_with_status    varchar(250)  NULL ,
	updated_at           datetime  NULL ,
	updated_by           varchar(250)  NULL ,
	webinar_banner       varchar(1000)  NULL ,
	webinar_expiry_date  datetime  NULL ,
	webinar_footer       varchar(250)  NULL ,
	webinar_include_calendar_invitation varchar(250)  NULL ,
	webinar_max_attendee varchar(250)  NULL ,
	webinar_registration_url varchar(250)  NULL ,
	webinar_send_personnel_notification boolean  NULL ,
	webinar_show_overview boolean  NULL ,
	webinar_show_speaker_on_overview boolean  NULL ,
	webinar_theme_color  varchar(250)  NULL ,
	webinar_welcome_message varchar(250)  NULL ,
	additional_editors   varchar(250)  NULL ,
	agenda_time_format   varchar(250)  NULL ,
	alternate_date       datetime  NULL ,
	alternate_end_date   datetime  NULL ,
	alternate_end_time   date  NULL ,
	alternate_start_time date  NULL ,
	briefing_type_name   varchar(255)  NULL ,
	employee_count       varchar(255)  NULL ,
	source_system_name   varchar(100)  NULL ,
	effective_start_date timestamp without time zone  NULL ,
	effective_end_date   timestamp without time zone  NULL ,
	current_flag         character varying(5)  NULL  ENCODE LZO,
	etl_created_date     timestamp without time zone  NULL ,
	etl_updated_date     timestamp without time zone  NULL ,
	deleted_flag         boolean  NULL  ENCODE RAW 
);

ALTER TABLE dims.dim_briefing
	ADD CONSTRAINT XPKDim_Briefing_ix PRIMARY KEY (briefing_key);

ALTER TABLE dims.dim_briefing
	ADD CONSTRAINT dim_briefing_dim_briefing_clone_from_briefing_key_fk FOREIGN KEY (clone_from_briefing_key) REFERENCES dims.dim_briefing(briefing_key);

ALTER TABLE dims.dim_briefing
	ADD CONSTRAINT dim_briefing_dim_briefing_clone_to_briefing_key_fk FOREIGN KEY (clone_to_briefing_key) REFERENCES dims.dim_briefing(briefing_key);

ALTER TABLE dims.dim_briefing
	ADD CONSTRAINT dim_briefing_dim_briefing_parent_briefing_key_fk FOREIGN KEY (parent_briefing_key) REFERENCES dims.dim_briefing(briefing_key);
